### ISSUE TITLE
inference using main file

### ISSUE THREAD

**Issue by ChethanN01** [katerynaCh/multimodal-emotion-recognition#6]
Initializing efficientnet
Traceback (most recent call last):
  File "D:\emotion_recongintion\multimodal-emotion-recognition-main\multimodal-emotion-recognition-main\main.py", line 158, in <module>
    test_data = get_test_set(opt, spatial_transform=video_transform)
  File "D:\emotion_recongintion\multimodal-emotion-recognition-main\multimodal-emotion-recognition-main\dataset.py", line 34, in get_test_set
    test_data = RAVDESS(
  File "D:\emotion_recongintion\multimodal-emotion-recognition-main\multimodal-emotion-recognition-main\ravdess.py", line 56, in __init__
    self.data = make_dataset(subset, annotation_path)
  File "D:\emotion_recongintion\multimodal-emotion-recognition-main\multimodal-emotion-recognition-main\ravdess.py", line 34, in make_dataset
    with open(annotation_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ravdess_preprocessing/annotations.txt'

please share the  sample data  with annotation file, i ravedess website dont give annotation data. please do let me know the format of annotation file required

**Comment by katerynaCh** [comment]
Hi, I suggest you to take a look at the "Dataset preparation" on github, as there are a few steps with data preprocessing before producing annotation files. Overall, the annotations.txt follow the format of:
fullpathtovideodata1.npy;fullpathtoaudio1.wav;classlabel;label;split
fullpathtovideodata2.npy;fullpathtoaudio2.wav;classlabel;label;split

example:
/home/RAVDESS/Actor_01/01-01-02-02-01-01-01_facecroppad.npy;/home/RAVDESS/Actor_01/03-01-02-02-01-01-01_croppad.wav;2;training
